name: Deploy Honeypot to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            script: |
            cd ~
            sudo pkill -f honeypot.py || true
            
            if [ ! -d "aws_honeypot_project" ]; then
              git clone https://github.com/JakubKasztelan/aws_honeypot_project.git
            fi
            
            git pull origin main
            
            sudo nohup python3 honeypot.py > /dev/null 2>&1 &
            
            sleep 2